### ISSUE TITLE
JSONDecodeError when starting Kraken

### ISSUE THREAD

**Issue by koflerm** [cloud-bulldozer/kraken#128]
We are having troubles to start kraken in our OpenShift 4.6 cluster. After the kraken pod starts it keeps crashing with a JSONDecodeError message:

```
2021-07-19 12:26:36,323 [INFO] Starting kraken
2021-07-19 12:26:36,330 [INFO] Initializing client to talk to the Kubernetes cluster
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:1020: InsecureRequestWarning: Unverified HTTPS request is being made to host 'api.ocp4.icp.infineon.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
 _              _
| | ___ __ __ _| | _____ _ __
| |/ / '__/ _` | |/ / _ \ '_ \
|   <| | | (_| |   <  __/ | | |
|_|\_\_|  \__,_|_|\_\___|_| |_|


Traceback (most recent call last):
  File "run_kraken.py", line 216, in <module>
    main(options.cfg)
  File "run_kraken.py", line 66, in main
    kubecli.find_kraken_node()
  File "/root/kraken/kraken/kubernetes/client.py", line 246, in find_kraken_node
    pod_json = json.loads(pod_json_str)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

We are using the following config.yaml file using a config map which is mounted as in your kubernetes instructions:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: kraken-config
  namespace: openshift-kraken   
data:
  config.yaml: |
    kraken:
        distribution: openshift                                # Distribution can be kubernetes or openshift
        kubeconfig_path: /root/.kube/config                    # Path to kubeconfig
        exit_on_failure: False                                 # Exit when a post action scenario fails
        litmus_version: v1.10.0                                # Litmus version to install
        litmus_uninstall: False                                # If you want to uninstall litmus if failure
        chaos_scenarios:                                       # List of policies/chaos scenarios to load
            -   pod_scenarios:
                - -    scenarios/customapp_pod.yml
                - -    scenarios/openshift_ingress_pod.yml
    cerberus:
        cerberus_enabled: False                                # Enable it when cerberus is previously installed
        cerberus_url:                                          # When cerberus_enabled is set to True, provide the url where cerberus publishes go/no-go signal

    performance_monitoring:
        deploy_dashboards: False                              # Install a mutable grafana and load the performance dashboards. Enable this only when running on OpenShift
        repo: "https://github.com/cloud-bulldozer/performance-dashboards.git"
        kube_burner_binary_url: "https://github.com/cloud-bulldozer/kube-burner/releases/download/v0.9.1/kube-burner-0.9.1-Linux-x86_64.tar.gz"
        capture_metrics: False
        config_path: config/kube_burner.yaml                  # Define the Elasticsearch url and index name in this config
        metrics_profile_path: config/metrics-aggregated.yaml
        prometheus_url:                                       # The prometheus url/route is automatically obtained in case of OpenShift, please set it when the distribution is Kubernetes.
        prometheus_bearer_token:                              # The bearer token is automatically obtained in case of OpenShift, please set it when the distribution is Kubernetes. This is needed to authenticate with prometheus.
        uuid:                                                 # uuid for the run is generated by default if not set
        enable_alerts: False                                  # Runs the queries specified in the alert profile and displays the info or exits 1 when severity=error
        alert_profile: config/alerts                          # Path to alert profile with the prometheus queries

    tunings:
        wait_duration: 60                                      # Duration to wait between each chaos scenario
        iterations: 1                                          # Number of times to execute the scenarios
        daemon_mode: False                                     # Iterations are set to infinity which means that the kraken will cause chaos forever
```

For the scenarios we are using the following config map:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: scenarios-config
  namespace: openshift-kraken  
data:
  customapp_pod.yml: |
    config:
      runStrategy:
        runs: 1
        maxSecondsBetweenRuns: 30
        minSecondsBetweenRuns: 1
    scenarios:
      - name: "delete customer pods"
        steps:
        - podAction:
            matches:
              - labels:
                  namespace: "customer"
                  selector: ""
            filters:
              - randomSample:
                  size: 1
            actions:
              - kill:
                  probability: 1
                  force: true
        - podAction:
            matches:
              - labels:
                  namespace: "customer"
                  selector: ""
            retries:
              retriesTimeout:
                timeout: 180

            actions:
              - checkPodCount:
                  count: 8
  openshift_ingress_pod.yml: |
    config:
      runStrategy:
        runs: 1
        maxSecondsBetweenRuns: 30
        minSecondsBetweenRuns: 1
    scenarios:
      - name: "delete openshift-ingress pods"
        steps:
        - podAction:
            matches:
              - labels:
                  namespace: "openshift-ingress"
                  selector: ""
            filters:
              - randomSample:
                  size: 1
            actions:
              - kill:
                  probability: 1
                  force: true
        - podAction:
            matches:
              - labels:
                  namespace: "openshift-ingress"
                  selector: ""
            retries:
              retriesTimeout:
                timeout: 180

            actions:
              - checkPodCount:
                  count: 2

```

Can you please help us here what is wrong with this configuration?
